# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import treestore_pb2 as treestore__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in treestore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TreeStoreServiceStub(object):
    """TreeStoreService provides hierarchical document storage with versioning
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreDocument = channel.unary_unary(
                '/treestore.TreeStoreService/StoreDocument',
                request_serializer=treestore__pb2.StoreDocumentRequest.SerializeToString,
                response_deserializer=treestore__pb2.StoreDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/treestore.TreeStoreService/GetDocument',
                request_serializer=treestore__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/treestore.TreeStoreService/DeleteDocument',
                request_serializer=treestore__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=treestore__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/treestore.TreeStoreService/GetNode',
                request_serializer=treestore__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/treestore.TreeStoreService/GetChildren',
                request_serializer=treestore__pb2.GetChildrenRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetChildrenResponse.FromString,
                _registered_method=True)
        self.GetSubtree = channel.unary_unary(
                '/treestore.TreeStoreService/GetSubtree',
                request_serializer=treestore__pb2.GetSubtreeRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetSubtreeResponse.FromString,
                _registered_method=True)
        self.GetAncestorPath = channel.unary_unary(
                '/treestore.TreeStoreService/GetAncestorPath',
                request_serializer=treestore__pb2.GetAncestorPathRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetAncestorPathResponse.FromString,
                _registered_method=True)
        self.SearchByKeyword = channel.unary_unary(
                '/treestore.TreeStoreService/SearchByKeyword',
                request_serializer=treestore__pb2.SearchRequest.SerializeToString,
                response_deserializer=treestore__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetNodesByPage = channel.unary_unary(
                '/treestore.TreeStoreService/GetNodesByPage',
                request_serializer=treestore__pb2.GetNodesByPageRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetNodesByPageResponse.FromString,
                _registered_method=True)
        self.GetVersionAsOf = channel.unary_unary(
                '/treestore.TreeStoreService/GetVersionAsOf',
                request_serializer=treestore__pb2.GetVersionAsOfRequest.SerializeToString,
                response_deserializer=treestore__pb2.PolicyVersion.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/treestore.TreeStoreService/ListVersions',
                request_serializer=treestore__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=treestore__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.StoreToolResult = channel.unary_unary(
                '/treestore.TreeStoreService/StoreToolResult',
                request_serializer=treestore__pb2.StoreToolResultRequest.SerializeToString,
                response_deserializer=treestore__pb2.StoreToolResultResponse.FromString,
                _registered_method=True)
        self.GetToolResults = channel.unary_unary(
                '/treestore.TreeStoreService/GetToolResults',
                request_serializer=treestore__pb2.GetToolResultsRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetToolResultsResponse.FromString,
                _registered_method=True)
        self.StoreTrajectory = channel.unary_unary(
                '/treestore.TreeStoreService/StoreTrajectory',
                request_serializer=treestore__pb2.StoreTrajectoryRequest.SerializeToString,
                response_deserializer=treestore__pb2.StoreTrajectoryResponse.FromString,
                _registered_method=True)
        self.GetTrajectories = channel.unary_unary(
                '/treestore.TreeStoreService/GetTrajectories',
                request_serializer=treestore__pb2.GetTrajectoriesRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetTrajectoriesResponse.FromString,
                _registered_method=True)
        self.StoreCrossReference = channel.unary_unary(
                '/treestore.TreeStoreService/StoreCrossReference',
                request_serializer=treestore__pb2.StoreCrossReferenceRequest.SerializeToString,
                response_deserializer=treestore__pb2.StoreCrossReferenceResponse.FromString,
                _registered_method=True)
        self.GetCrossReferences = channel.unary_unary(
                '/treestore.TreeStoreService/GetCrossReferences',
                request_serializer=treestore__pb2.GetCrossReferencesRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetCrossReferencesResponse.FromString,
                _registered_method=True)
        self.StoreContradiction = channel.unary_unary(
                '/treestore.TreeStoreService/StoreContradiction',
                request_serializer=treestore__pb2.StoreContradictionRequest.SerializeToString,
                response_deserializer=treestore__pb2.StoreContradictionResponse.FromString,
                _registered_method=True)
        self.StorePrompt = channel.unary_unary(
                '/treestore.TreeStoreService/StorePrompt',
                request_serializer=treestore__pb2.StorePromptRequest.SerializeToString,
                response_deserializer=treestore__pb2.StorePromptResponse.FromString,
                _registered_method=True)
        self.GetPrompt = channel.unary_unary(
                '/treestore.TreeStoreService/GetPrompt',
                request_serializer=treestore__pb2.GetPromptRequest.SerializeToString,
                response_deserializer=treestore__pb2.GetPromptResponse.FromString,
                _registered_method=True)
        self.RecordPromptUsage = channel.unary_unary(
                '/treestore.TreeStoreService/RecordPromptUsage',
                request_serializer=treestore__pb2.RecordPromptUsageRequest.SerializeToString,
                response_deserializer=treestore__pb2.RecordPromptUsageResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/treestore.TreeStoreService/Health',
                request_serializer=treestore__pb2.HealthRequest.SerializeToString,
                response_deserializer=treestore__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/treestore.TreeStoreService/Stats',
                request_serializer=treestore__pb2.StatsRequest.SerializeToString,
                response_deserializer=treestore__pb2.StatsResponse.FromString,
                _registered_method=True)


class TreeStoreServiceServicer(object):
    """TreeStoreService provides hierarchical document storage with versioning
    """

    def StoreDocument(self, request, context):
        """========== Document Operations (3 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """========== Node Operations (4 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubtree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAncestorPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByKeyword(self, request, context):
        """========== Search Operations (2 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodesByPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersionAsOf(self, request, context):
        """========== Version Operations (2 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreToolResult(self, request, context):
        """========== Metadata Operations (7 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrajectories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreCrossReference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossReferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreContradiction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorePrompt(self, request, context):
        """========== Prompt Operations (3 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPromptUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """========== Health & Status (2 methods) ==========
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreeStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreDocument,
                    request_deserializer=treestore__pb2.StoreDocumentRequest.FromString,
                    response_serializer=treestore__pb2.StoreDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=treestore__pb2.GetDocumentRequest.FromString,
                    response_serializer=treestore__pb2.GetDocumentResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=treestore__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=treestore__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=treestore__pb2.GetNodeRequest.FromString,
                    response_serializer=treestore__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=treestore__pb2.GetChildrenRequest.FromString,
                    response_serializer=treestore__pb2.GetChildrenResponse.SerializeToString,
            ),
            'GetSubtree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubtree,
                    request_deserializer=treestore__pb2.GetSubtreeRequest.FromString,
                    response_serializer=treestore__pb2.GetSubtreeResponse.SerializeToString,
            ),
            'GetAncestorPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAncestorPath,
                    request_deserializer=treestore__pb2.GetAncestorPathRequest.FromString,
                    response_serializer=treestore__pb2.GetAncestorPathResponse.SerializeToString,
            ),
            'SearchByKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByKeyword,
                    request_deserializer=treestore__pb2.SearchRequest.FromString,
                    response_serializer=treestore__pb2.SearchResponse.SerializeToString,
            ),
            'GetNodesByPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodesByPage,
                    request_deserializer=treestore__pb2.GetNodesByPageRequest.FromString,
                    response_serializer=treestore__pb2.GetNodesByPageResponse.SerializeToString,
            ),
            'GetVersionAsOf': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersionAsOf,
                    request_deserializer=treestore__pb2.GetVersionAsOfRequest.FromString,
                    response_serializer=treestore__pb2.PolicyVersion.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=treestore__pb2.ListVersionsRequest.FromString,
                    response_serializer=treestore__pb2.ListVersionsResponse.SerializeToString,
            ),
            'StoreToolResult': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreToolResult,
                    request_deserializer=treestore__pb2.StoreToolResultRequest.FromString,
                    response_serializer=treestore__pb2.StoreToolResultResponse.SerializeToString,
            ),
            'GetToolResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolResults,
                    request_deserializer=treestore__pb2.GetToolResultsRequest.FromString,
                    response_serializer=treestore__pb2.GetToolResultsResponse.SerializeToString,
            ),
            'StoreTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTrajectory,
                    request_deserializer=treestore__pb2.StoreTrajectoryRequest.FromString,
                    response_serializer=treestore__pb2.StoreTrajectoryResponse.SerializeToString,
            ),
            'GetTrajectories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrajectories,
                    request_deserializer=treestore__pb2.GetTrajectoriesRequest.FromString,
                    response_serializer=treestore__pb2.GetTrajectoriesResponse.SerializeToString,
            ),
            'StoreCrossReference': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreCrossReference,
                    request_deserializer=treestore__pb2.StoreCrossReferenceRequest.FromString,
                    response_serializer=treestore__pb2.StoreCrossReferenceResponse.SerializeToString,
            ),
            'GetCrossReferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossReferences,
                    request_deserializer=treestore__pb2.GetCrossReferencesRequest.FromString,
                    response_serializer=treestore__pb2.GetCrossReferencesResponse.SerializeToString,
            ),
            'StoreContradiction': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreContradiction,
                    request_deserializer=treestore__pb2.StoreContradictionRequest.FromString,
                    response_serializer=treestore__pb2.StoreContradictionResponse.SerializeToString,
            ),
            'StorePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.StorePrompt,
                    request_deserializer=treestore__pb2.StorePromptRequest.FromString,
                    response_serializer=treestore__pb2.StorePromptResponse.SerializeToString,
            ),
            'GetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrompt,
                    request_deserializer=treestore__pb2.GetPromptRequest.FromString,
                    response_serializer=treestore__pb2.GetPromptResponse.SerializeToString,
            ),
            'RecordPromptUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPromptUsage,
                    request_deserializer=treestore__pb2.RecordPromptUsageRequest.FromString,
                    response_serializer=treestore__pb2.RecordPromptUsageResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=treestore__pb2.HealthRequest.FromString,
                    response_serializer=treestore__pb2.HealthResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=treestore__pb2.StatsRequest.FromString,
                    response_serializer=treestore__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'treestore.TreeStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('treestore.TreeStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TreeStoreService(object):
    """TreeStoreService provides hierarchical document storage with versioning
    """

    @staticmethod
    def StoreDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/StoreDocument',
            treestore__pb2.StoreDocumentRequest.SerializeToString,
            treestore__pb2.StoreDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetDocument',
            treestore__pb2.GetDocumentRequest.SerializeToString,
            treestore__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/DeleteDocument',
            treestore__pb2.DeleteDocumentRequest.SerializeToString,
            treestore__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetNode',
            treestore__pb2.GetNodeRequest.SerializeToString,
            treestore__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetChildren',
            treestore__pb2.GetChildrenRequest.SerializeToString,
            treestore__pb2.GetChildrenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubtree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetSubtree',
            treestore__pb2.GetSubtreeRequest.SerializeToString,
            treestore__pb2.GetSubtreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAncestorPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetAncestorPath',
            treestore__pb2.GetAncestorPathRequest.SerializeToString,
            treestore__pb2.GetAncestorPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/SearchByKeyword',
            treestore__pb2.SearchRequest.SerializeToString,
            treestore__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodesByPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetNodesByPage',
            treestore__pb2.GetNodesByPageRequest.SerializeToString,
            treestore__pb2.GetNodesByPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersionAsOf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetVersionAsOf',
            treestore__pb2.GetVersionAsOfRequest.SerializeToString,
            treestore__pb2.PolicyVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/ListVersions',
            treestore__pb2.ListVersionsRequest.SerializeToString,
            treestore__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreToolResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/StoreToolResult',
            treestore__pb2.StoreToolResultRequest.SerializeToString,
            treestore__pb2.StoreToolResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetToolResults',
            treestore__pb2.GetToolResultsRequest.SerializeToString,
            treestore__pb2.GetToolResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/StoreTrajectory',
            treestore__pb2.StoreTrajectoryRequest.SerializeToString,
            treestore__pb2.StoreTrajectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrajectories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetTrajectories',
            treestore__pb2.GetTrajectoriesRequest.SerializeToString,
            treestore__pb2.GetTrajectoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreCrossReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/StoreCrossReference',
            treestore__pb2.StoreCrossReferenceRequest.SerializeToString,
            treestore__pb2.StoreCrossReferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrossReferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetCrossReferences',
            treestore__pb2.GetCrossReferencesRequest.SerializeToString,
            treestore__pb2.GetCrossReferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreContradiction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/StoreContradiction',
            treestore__pb2.StoreContradictionRequest.SerializeToString,
            treestore__pb2.StoreContradictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StorePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/StorePrompt',
            treestore__pb2.StorePromptRequest.SerializeToString,
            treestore__pb2.StorePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/GetPrompt',
            treestore__pb2.GetPromptRequest.SerializeToString,
            treestore__pb2.GetPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordPromptUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/RecordPromptUsage',
            treestore__pb2.RecordPromptUsageRequest.SerializeToString,
            treestore__pb2.RecordPromptUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/Health',
            treestore__pb2.HealthRequest.SerializeToString,
            treestore__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treestore.TreeStoreService/Stats',
            treestore__pb2.StatsRequest.SerializeToString,
            treestore__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
