// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/treestore.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TreeStoreService_StoreDocument_FullMethodName       = "/treestore.TreeStoreService/StoreDocument"
	TreeStoreService_GetDocument_FullMethodName         = "/treestore.TreeStoreService/GetDocument"
	TreeStoreService_DeleteDocument_FullMethodName      = "/treestore.TreeStoreService/DeleteDocument"
	TreeStoreService_GetNode_FullMethodName             = "/treestore.TreeStoreService/GetNode"
	TreeStoreService_GetChildren_FullMethodName         = "/treestore.TreeStoreService/GetChildren"
	TreeStoreService_GetSubtree_FullMethodName          = "/treestore.TreeStoreService/GetSubtree"
	TreeStoreService_GetAncestorPath_FullMethodName     = "/treestore.TreeStoreService/GetAncestorPath"
	TreeStoreService_SearchByKeyword_FullMethodName     = "/treestore.TreeStoreService/SearchByKeyword"
	TreeStoreService_GetNodesByPage_FullMethodName      = "/treestore.TreeStoreService/GetNodesByPage"
	TreeStoreService_GetVersionAsOf_FullMethodName      = "/treestore.TreeStoreService/GetVersionAsOf"
	TreeStoreService_ListVersions_FullMethodName        = "/treestore.TreeStoreService/ListVersions"
	TreeStoreService_StoreToolResult_FullMethodName     = "/treestore.TreeStoreService/StoreToolResult"
	TreeStoreService_GetToolResults_FullMethodName      = "/treestore.TreeStoreService/GetToolResults"
	TreeStoreService_StoreTrajectory_FullMethodName     = "/treestore.TreeStoreService/StoreTrajectory"
	TreeStoreService_GetTrajectories_FullMethodName     = "/treestore.TreeStoreService/GetTrajectories"
	TreeStoreService_StoreCrossReference_FullMethodName = "/treestore.TreeStoreService/StoreCrossReference"
	TreeStoreService_GetCrossReferences_FullMethodName  = "/treestore.TreeStoreService/GetCrossReferences"
	TreeStoreService_StoreContradiction_FullMethodName  = "/treestore.TreeStoreService/StoreContradiction"
	TreeStoreService_StorePrompt_FullMethodName         = "/treestore.TreeStoreService/StorePrompt"
	TreeStoreService_GetPrompt_FullMethodName           = "/treestore.TreeStoreService/GetPrompt"
	TreeStoreService_RecordPromptUsage_FullMethodName   = "/treestore.TreeStoreService/RecordPromptUsage"
	TreeStoreService_Health_FullMethodName              = "/treestore.TreeStoreService/Health"
	TreeStoreService_Stats_FullMethodName               = "/treestore.TreeStoreService/Stats"
)

// TreeStoreServiceClient is the client API for TreeStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TreeStoreService provides hierarchical document storage with versioning
type TreeStoreServiceClient interface {
	// ========== Document Operations (3 methods) ==========
	StoreDocument(ctx context.Context, in *StoreDocumentRequest, opts ...grpc.CallOption) (*StoreDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	// ========== Node Operations (4 methods) ==========
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error)
	GetSubtree(ctx context.Context, in *GetSubtreeRequest, opts ...grpc.CallOption) (*GetSubtreeResponse, error)
	GetAncestorPath(ctx context.Context, in *GetAncestorPathRequest, opts ...grpc.CallOption) (*GetAncestorPathResponse, error)
	// ========== Search Operations (2 methods) ==========
	SearchByKeyword(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetNodesByPage(ctx context.Context, in *GetNodesByPageRequest, opts ...grpc.CallOption) (*GetNodesByPageResponse, error)
	// ========== Version Operations (2 methods) ==========
	GetVersionAsOf(ctx context.Context, in *GetVersionAsOfRequest, opts ...grpc.CallOption) (*PolicyVersion, error)
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
	// ========== Metadata Operations (7 methods) ==========
	StoreToolResult(ctx context.Context, in *StoreToolResultRequest, opts ...grpc.CallOption) (*StoreToolResultResponse, error)
	GetToolResults(ctx context.Context, in *GetToolResultsRequest, opts ...grpc.CallOption) (*GetToolResultsResponse, error)
	StoreTrajectory(ctx context.Context, in *StoreTrajectoryRequest, opts ...grpc.CallOption) (*StoreTrajectoryResponse, error)
	GetTrajectories(ctx context.Context, in *GetTrajectoriesRequest, opts ...grpc.CallOption) (*GetTrajectoriesResponse, error)
	StoreCrossReference(ctx context.Context, in *StoreCrossReferenceRequest, opts ...grpc.CallOption) (*StoreCrossReferenceResponse, error)
	GetCrossReferences(ctx context.Context, in *GetCrossReferencesRequest, opts ...grpc.CallOption) (*GetCrossReferencesResponse, error)
	StoreContradiction(ctx context.Context, in *StoreContradictionRequest, opts ...grpc.CallOption) (*StoreContradictionResponse, error)
	// ========== Prompt Operations (3 methods) ==========
	StorePrompt(ctx context.Context, in *StorePromptRequest, opts ...grpc.CallOption) (*StorePromptResponse, error)
	GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*GetPromptResponse, error)
	RecordPromptUsage(ctx context.Context, in *RecordPromptUsageRequest, opts ...grpc.CallOption) (*RecordPromptUsageResponse, error)
	// ========== Health & Status (2 methods) ==========
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type treeStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeStoreServiceClient(cc grpc.ClientConnInterface) TreeStoreServiceClient {
	return &treeStoreServiceClient{cc}
}

func (c *treeStoreServiceClient) StoreDocument(ctx context.Context, in *StoreDocumentRequest, opts ...grpc.CallOption) (*StoreDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreDocumentResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_StoreDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChildrenResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetSubtree(ctx context.Context, in *GetSubtreeRequest, opts ...grpc.CallOption) (*GetSubtreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubtreeResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetSubtree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetAncestorPath(ctx context.Context, in *GetAncestorPathRequest, opts ...grpc.CallOption) (*GetAncestorPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAncestorPathResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetAncestorPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) SearchByKeyword(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_SearchByKeyword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetNodesByPage(ctx context.Context, in *GetNodesByPageRequest, opts ...grpc.CallOption) (*GetNodesByPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesByPageResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetNodesByPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetVersionAsOf(ctx context.Context, in *GetVersionAsOfRequest, opts ...grpc.CallOption) (*PolicyVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyVersion)
	err := c.cc.Invoke(ctx, TreeStoreService_GetVersionAsOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) StoreToolResult(ctx context.Context, in *StoreToolResultRequest, opts ...grpc.CallOption) (*StoreToolResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreToolResultResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_StoreToolResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetToolResults(ctx context.Context, in *GetToolResultsRequest, opts ...grpc.CallOption) (*GetToolResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolResultsResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetToolResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) StoreTrajectory(ctx context.Context, in *StoreTrajectoryRequest, opts ...grpc.CallOption) (*StoreTrajectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreTrajectoryResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_StoreTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetTrajectories(ctx context.Context, in *GetTrajectoriesRequest, opts ...grpc.CallOption) (*GetTrajectoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrajectoriesResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetTrajectories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) StoreCrossReference(ctx context.Context, in *StoreCrossReferenceRequest, opts ...grpc.CallOption) (*StoreCrossReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreCrossReferenceResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_StoreCrossReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetCrossReferences(ctx context.Context, in *GetCrossReferencesRequest, opts ...grpc.CallOption) (*GetCrossReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCrossReferencesResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetCrossReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) StoreContradiction(ctx context.Context, in *StoreContradictionRequest, opts ...grpc.CallOption) (*StoreContradictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreContradictionResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_StoreContradiction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) StorePrompt(ctx context.Context, in *StorePromptRequest, opts ...grpc.CallOption) (*StorePromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorePromptResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_StorePrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*GetPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPromptResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_GetPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) RecordPromptUsage(ctx context.Context, in *RecordPromptUsageRequest, opts ...grpc.CallOption) (*RecordPromptUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordPromptUsageResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_RecordPromptUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeStoreServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, TreeStoreService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeStoreServiceServer is the server API for TreeStoreService service.
// All implementations must embed UnimplementedTreeStoreServiceServer
// for forward compatibility.
//
// TreeStoreService provides hierarchical document storage with versioning
type TreeStoreServiceServer interface {
	// ========== Document Operations (3 methods) ==========
	StoreDocument(context.Context, *StoreDocumentRequest) (*StoreDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	// ========== Node Operations (4 methods) ==========
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error)
	GetSubtree(context.Context, *GetSubtreeRequest) (*GetSubtreeResponse, error)
	GetAncestorPath(context.Context, *GetAncestorPathRequest) (*GetAncestorPathResponse, error)
	// ========== Search Operations (2 methods) ==========
	SearchByKeyword(context.Context, *SearchRequest) (*SearchResponse, error)
	GetNodesByPage(context.Context, *GetNodesByPageRequest) (*GetNodesByPageResponse, error)
	// ========== Version Operations (2 methods) ==========
	GetVersionAsOf(context.Context, *GetVersionAsOfRequest) (*PolicyVersion, error)
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	// ========== Metadata Operations (7 methods) ==========
	StoreToolResult(context.Context, *StoreToolResultRequest) (*StoreToolResultResponse, error)
	GetToolResults(context.Context, *GetToolResultsRequest) (*GetToolResultsResponse, error)
	StoreTrajectory(context.Context, *StoreTrajectoryRequest) (*StoreTrajectoryResponse, error)
	GetTrajectories(context.Context, *GetTrajectoriesRequest) (*GetTrajectoriesResponse, error)
	StoreCrossReference(context.Context, *StoreCrossReferenceRequest) (*StoreCrossReferenceResponse, error)
	GetCrossReferences(context.Context, *GetCrossReferencesRequest) (*GetCrossReferencesResponse, error)
	StoreContradiction(context.Context, *StoreContradictionRequest) (*StoreContradictionResponse, error)
	// ========== Prompt Operations (3 methods) ==========
	StorePrompt(context.Context, *StorePromptRequest) (*StorePromptResponse, error)
	GetPrompt(context.Context, *GetPromptRequest) (*GetPromptResponse, error)
	RecordPromptUsage(context.Context, *RecordPromptUsageRequest) (*RecordPromptUsageResponse, error)
	// ========== Health & Status (2 methods) ==========
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedTreeStoreServiceServer()
}

// UnimplementedTreeStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTreeStoreServiceServer struct{}

func (UnimplementedTreeStoreServiceServer) StoreDocument(context.Context, *StoreDocumentRequest) (*StoreDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreDocument not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedTreeStoreServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildren not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetSubtree(context.Context, *GetSubtreeRequest) (*GetSubtreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubtree not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetAncestorPath(context.Context, *GetAncestorPathRequest) (*GetAncestorPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAncestorPath not implemented")
}
func (UnimplementedTreeStoreServiceServer) SearchByKeyword(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByKeyword not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetNodesByPage(context.Context, *GetNodesByPageRequest) (*GetNodesByPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodesByPage not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetVersionAsOf(context.Context, *GetVersionAsOfRequest) (*PolicyVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersionAsOf not implemented")
}
func (UnimplementedTreeStoreServiceServer) ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedTreeStoreServiceServer) StoreToolResult(context.Context, *StoreToolResultRequest) (*StoreToolResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreToolResult not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetToolResults(context.Context, *GetToolResultsRequest) (*GetToolResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolResults not implemented")
}
func (UnimplementedTreeStoreServiceServer) StoreTrajectory(context.Context, *StoreTrajectoryRequest) (*StoreTrajectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTrajectory not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetTrajectories(context.Context, *GetTrajectoriesRequest) (*GetTrajectoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrajectories not implemented")
}
func (UnimplementedTreeStoreServiceServer) StoreCrossReference(context.Context, *StoreCrossReferenceRequest) (*StoreCrossReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreCrossReference not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetCrossReferences(context.Context, *GetCrossReferencesRequest) (*GetCrossReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCrossReferences not implemented")
}
func (UnimplementedTreeStoreServiceServer) StoreContradiction(context.Context, *StoreContradictionRequest) (*StoreContradictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreContradiction not implemented")
}
func (UnimplementedTreeStoreServiceServer) StorePrompt(context.Context, *StorePromptRequest) (*StorePromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorePrompt not implemented")
}
func (UnimplementedTreeStoreServiceServer) GetPrompt(context.Context, *GetPromptRequest) (*GetPromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrompt not implemented")
}
func (UnimplementedTreeStoreServiceServer) RecordPromptUsage(context.Context, *RecordPromptUsageRequest) (*RecordPromptUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordPromptUsage not implemented")
}
func (UnimplementedTreeStoreServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTreeStoreServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedTreeStoreServiceServer) mustEmbedUnimplementedTreeStoreServiceServer() {}
func (UnimplementedTreeStoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeTreeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeStoreServiceServer will
// result in compilation errors.
type UnsafeTreeStoreServiceServer interface {
	mustEmbedUnimplementedTreeStoreServiceServer()
}

func RegisterTreeStoreServiceServer(s grpc.ServiceRegistrar, srv TreeStoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedTreeStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TreeStoreService_ServiceDesc, srv)
}

func _TreeStoreService_StoreDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).StoreDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_StoreDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).StoreDocument(ctx, req.(*StoreDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetChildren(ctx, req.(*GetChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetSubtree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetSubtree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetSubtree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetSubtree(ctx, req.(*GetSubtreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetAncestorPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestorPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetAncestorPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetAncestorPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetAncestorPath(ctx, req.(*GetAncestorPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_SearchByKeyword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).SearchByKeyword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_SearchByKeyword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).SearchByKeyword(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetNodesByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetNodesByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetNodesByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetNodesByPage(ctx, req.(*GetNodesByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetVersionAsOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionAsOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetVersionAsOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetVersionAsOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetVersionAsOf(ctx, req.(*GetVersionAsOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_StoreToolResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreToolResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).StoreToolResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_StoreToolResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).StoreToolResult(ctx, req.(*StoreToolResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetToolResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetToolResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetToolResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetToolResults(ctx, req.(*GetToolResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_StoreTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).StoreTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_StoreTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).StoreTrajectory(ctx, req.(*StoreTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetTrajectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrajectoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetTrajectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetTrajectories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetTrajectories(ctx, req.(*GetTrajectoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_StoreCrossReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreCrossReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).StoreCrossReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_StoreCrossReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).StoreCrossReference(ctx, req.(*StoreCrossReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetCrossReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrossReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetCrossReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetCrossReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetCrossReferences(ctx, req.(*GetCrossReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_StoreContradiction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreContradictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).StoreContradiction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_StoreContradiction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).StoreContradiction(ctx, req.(*StoreContradictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_StorePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).StorePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_StorePrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).StorePrompt(ctx, req.(*StorePromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_GetPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).GetPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_GetPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).GetPrompt(ctx, req.(*GetPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_RecordPromptUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPromptUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).RecordPromptUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_RecordPromptUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).RecordPromptUsage(ctx, req.(*RecordPromptUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeStoreService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeStoreServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeStoreService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeStoreServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TreeStoreService_ServiceDesc is the grpc.ServiceDesc for TreeStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreeStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treestore.TreeStoreService",
	HandlerType: (*TreeStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreDocument",
			Handler:    _TreeStoreService_StoreDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _TreeStoreService_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _TreeStoreService_DeleteDocument_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _TreeStoreService_GetNode_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _TreeStoreService_GetChildren_Handler,
		},
		{
			MethodName: "GetSubtree",
			Handler:    _TreeStoreService_GetSubtree_Handler,
		},
		{
			MethodName: "GetAncestorPath",
			Handler:    _TreeStoreService_GetAncestorPath_Handler,
		},
		{
			MethodName: "SearchByKeyword",
			Handler:    _TreeStoreService_SearchByKeyword_Handler,
		},
		{
			MethodName: "GetNodesByPage",
			Handler:    _TreeStoreService_GetNodesByPage_Handler,
		},
		{
			MethodName: "GetVersionAsOf",
			Handler:    _TreeStoreService_GetVersionAsOf_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _TreeStoreService_ListVersions_Handler,
		},
		{
			MethodName: "StoreToolResult",
			Handler:    _TreeStoreService_StoreToolResult_Handler,
		},
		{
			MethodName: "GetToolResults",
			Handler:    _TreeStoreService_GetToolResults_Handler,
		},
		{
			MethodName: "StoreTrajectory",
			Handler:    _TreeStoreService_StoreTrajectory_Handler,
		},
		{
			MethodName: "GetTrajectories",
			Handler:    _TreeStoreService_GetTrajectories_Handler,
		},
		{
			MethodName: "StoreCrossReference",
			Handler:    _TreeStoreService_StoreCrossReference_Handler,
		},
		{
			MethodName: "GetCrossReferences",
			Handler:    _TreeStoreService_GetCrossReferences_Handler,
		},
		{
			MethodName: "StoreContradiction",
			Handler:    _TreeStoreService_StoreContradiction_Handler,
		},
		{
			MethodName: "StorePrompt",
			Handler:    _TreeStoreService_StorePrompt_Handler,
		},
		{
			MethodName: "GetPrompt",
			Handler:    _TreeStoreService_GetPrompt_Handler,
		},
		{
			MethodName: "RecordPromptUsage",
			Handler:    _TreeStoreService_RecordPromptUsage_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TreeStoreService_Health_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _TreeStoreService_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/treestore.proto",
}
